"""Add checklist_states to Planning model

Revision ID: 03102d9a4471
Revises: 
Create Date: 2025-06-01 17:57:54.429212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03102d9a4471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_states', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.drop_column('checklist_states')

    # ### end Alembic commands ###
